'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ISISEASY
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contracts.ResponseType", [Namespace]:="http://isisbilisim.com.tr/data/einvoice"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ContractsResponseType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ByteDataField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommercialResponseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CommercialResponseEnvelopeUUIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ETTNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnvelopeUUIDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExtensionsField As System.Collections.Generic.List(Of ISISEASY.InvoiceExtension)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GIBCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GIBMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProfileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReceiverAliasField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReceiverVKNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SenderAliasField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SenderVKNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As ISISEASY.ContractsStatusType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ByteData() As Byte()
            Get
                Return Me.ByteDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ByteDataField, value) <> true) Then
                    Me.ByteDataField = value
                    Me.RaisePropertyChanged("ByteData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CommercialResponse() As String
            Get
                Return Me.CommercialResponseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommercialResponseField, value) <> true) Then
                    Me.CommercialResponseField = value
                    Me.RaisePropertyChanged("CommercialResponse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CommercialResponseEnvelopeUUID() As String
            Get
                Return Me.CommercialResponseEnvelopeUUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CommercialResponseEnvelopeUUIDField, value) <> true) Then
                    Me.CommercialResponseEnvelopeUUIDField = value
                    Me.RaisePropertyChanged("CommercialResponseEnvelopeUUID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ETTN() As String
            Get
                Return Me.ETTNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ETTNField, value) <> true) Then
                    Me.ETTNField = value
                    Me.RaisePropertyChanged("ETTN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EnvelopeUUID() As String
            Get
                Return Me.EnvelopeUUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EnvelopeUUIDField, value) <> true) Then
                    Me.EnvelopeUUIDField = value
                    Me.RaisePropertyChanged("EnvelopeUUID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Extensions() As System.Collections.Generic.List(Of ISISEASY.InvoiceExtension)
            Get
                Return Me.ExtensionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExtensionsField, value) <> true) Then
                    Me.ExtensionsField = value
                    Me.RaisePropertyChanged("Extensions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GIBCode() As Integer
            Get
                Return Me.GIBCodeField
            End Get
            Set
                If (Me.GIBCodeField.Equals(value) <> true) Then
                    Me.GIBCodeField = value
                    Me.RaisePropertyChanged("GIBCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GIBMessage() As String
            Get
                Return Me.GIBMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GIBMessageField, value) <> true) Then
                    Me.GIBMessageField = value
                    Me.RaisePropertyChanged("GIBMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As String
            Get
                Return Me.IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IDField, value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Profile() As String
            Get
                Return Me.ProfileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ProfileField, value) <> true) Then
                    Me.ProfileField = value
                    Me.RaisePropertyChanged("Profile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReceiverAlias() As String
            Get
                Return Me.ReceiverAliasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReceiverAliasField, value) <> true) Then
                    Me.ReceiverAliasField = value
                    Me.RaisePropertyChanged("ReceiverAlias")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReceiverVKN() As String
            Get
                Return Me.ReceiverVKNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReceiverVKNField, value) <> true) Then
                    Me.ReceiverVKNField = value
                    Me.RaisePropertyChanged("ReceiverVKN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SenderAlias() As String
            Get
                Return Me.SenderAliasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SenderAliasField, value) <> true) Then
                    Me.SenderAliasField = value
                    Me.RaisePropertyChanged("SenderAlias")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SenderVKN() As String
            Get
                Return Me.SenderVKNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SenderVKNField, value) <> true) Then
                    Me.SenderVKNField = value
                    Me.RaisePropertyChanged("SenderVKN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As ISISEASY.ContractsStatusType
            Get
                Return Me.StatusField
            End Get
            Set
                If (Me.StatusField.Equals(value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InvoiceExtension", [Namespace]:="http://isisbilisim.com.tr/data/einvoice"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InvoiceExtension
        Inherits ISISEASY.Extension
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreateDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ETTNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsActiveField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UpdatedDateField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCodeField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CreateDate() As Date
            Get
                Return Me.CreateDateField
            End Get
            Set
                If (Me.CreateDateField.Equals(value) <> true) Then
                    Me.CreateDateField = value
                    Me.RaisePropertyChanged("CreateDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ETTN() As String
            Get
                Return Me.ETTNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ETTNField, value) <> true) Then
                    Me.ETTNField = value
                    Me.RaisePropertyChanged("ETTN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IsActive() As Boolean
            Get
                Return Me.IsActiveField
            End Get
            Set
                If (Me.IsActiveField.Equals(value) <> true) Then
                    Me.IsActiveField = value
                    Me.RaisePropertyChanged("IsActive")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property UpdatedDate() As System.Nullable(Of Date)
            Get
                Return Me.UpdatedDateField
            End Get
            Set
                If (Me.UpdatedDateField.Equals(value) <> true) Then
                    Me.UpdatedDateField = value
                    Me.RaisePropertyChanged("UpdatedDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property UserCode() As Integer
            Get
                Return Me.UserCodeField
            End Get
            Set
                If (Me.UserCodeField.Equals(value) <> true) Then
                    Me.UserCodeField = value
                    Me.RaisePropertyChanged("UserCode")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contracts.StatusType", [Namespace]:="http://isisbilisim.com.tr/data/einvoice")>  _
    Public Enum ContractsStatusType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OK = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [ERROR] = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PROCCESSING = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ACCEPTED = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        REJECTED = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Extension", [Namespace]:="http://isisbilisim.com.tr/data/einvoice"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(ISISEASY.InvoiceExtension))>  _
    Partial Public Class Extension
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StructureField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValuePart1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValuePart2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValuePart3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValuePart4Field As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property [Structure]() As String
            Get
                Return Me.StructureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StructureField, value) <> true) Then
                    Me.StructureField = value
                    Me.RaisePropertyChanged("Structure")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValuePart1() As String
            Get
                Return Me.ValuePart1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValuePart1Field, value) <> true) Then
                    Me.ValuePart1Field = value
                    Me.RaisePropertyChanged("ValuePart1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValuePart2() As String
            Get
                Return Me.ValuePart2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValuePart2Field, value) <> true) Then
                    Me.ValuePart2Field = value
                    Me.RaisePropertyChanged("ValuePart2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValuePart3() As String
            Get
                Return Me.ValuePart3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValuePart3Field, value) <> true) Then
                    Me.ValuePart3Field = value
                    Me.RaisePropertyChanged("ValuePart3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValuePart4() As String
            Get
                Return Me.ValuePart4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValuePart4Field, value) <> true) Then
                    Me.ValuePart4Field = value
                    Me.RaisePropertyChanged("ValuePart4")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contracts.CommercialResponseType", [Namespace]:="http://isisbilisim.com.tr/data/einvoice")>  _
    Public Enum ContractsCommercialResponseType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ACCEPTED = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        REJECTED = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Contracts.DirectionType", [Namespace]:="http://isisbilisim.com.tr/data/einvoice")>  _
    Public Enum ContractsDirectionType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INBOUND = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OUTBOUND = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Enums.PDFType", [Namespace]:="http://isisbilisim.com.tr/core/enums")>  _
    Public Enum EnumsPDFType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NORMAL = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ATTACHMENT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DETAIL = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PREPRINTED = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LEGAL = 4
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://isisbilisim.com.tr/services/einvoice", ConfigurationName:="ISISEASY.IEasy")>  _
    Public Interface IEasy
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendInvoiceResponse")>  _
        Function SendInvoice(ByVal VKN As String, ByVal SenderAlias As String, ByVal ReceiverAlias As String, ByVal ByteData() As Byte) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendEnvelope", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendEnvelopeResponse")>  _
        Function SendEnvelope(ByVal VKN As String, ByVal ByteData() As Byte) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendResponse", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/SendResponseResponse")>  _
        Function SendResponse(ByVal VKN As String, ByVal ETTN As String, ByVal Response As ISISEASY.ContractsCommercialResponseType, ByVal Reason As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetInvoiceResponse")>  _
        Function GetInvoice(ByVal VKN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetSingleInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetSingleInvoiceResponse")>  _
        Function GetSingleInvoice(ByVal VKN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetStatus", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetStatusResponse")>  _
        Function GetStatus(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetMultipleItemStatus", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetMultipleItemStatusResponse")>  _
        Function GetMultipleItemStatus(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTNList As System.Collections.Generic.List(Of String)) As System.Collections.Generic.List(Of ISISEASY.ContractsResponseType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetSingleEnvelope", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetSingleEnvelopeResponse")>  _
        Function GetSingleEnvelope(ByVal VKN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetEnvelope", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetEnvelopeResponse")>  _
        Function GetEnvelope(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetPostboxList", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetPostboxListResponse")>  _
        Function GetPostboxList(ByVal ReceiverVKN As String) As System.Collections.Generic.List(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetPdfInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/GetPdfInvoiceResponse")>  _
        Function GetPdfInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal PDFType As System.Collections.Generic.List(Of ISISEASY.EnumsPDFType)) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveDone", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveDoneResponse")>  _
        Function ReceiveDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveEnvelopeDone", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveEnvelopeDoneResponse")>  _
        Function ReceiveEnvelopeDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveInvoiceDone", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/ReceiveInvoiceDoneResponse")>  _
        Function ReceiveInvoiceDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/AcceptInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/AcceptInvoiceResponse")>  _
        Function AcceptInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/RejectInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/RejectInvoiceResponse")>  _
        Function RejectInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/ApproveInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/ApproveInvoiceResponse")>  _
        Function ApproveInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://isisbilisim.com.tr/services/einvoice/IEasy/DenyInvoice", ReplyAction:="http://isisbilisim.com.tr/services/einvoice/IEasy/DenyInvoiceResponse")>  _
        Function DenyInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String, ByVal ReservedDate As System.Nullable(Of Date)) As ISISEASY.ContractsResponseType
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEasyChannel
        Inherits ISISEASY.IEasy, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EasyClient
        Inherits System.ServiceModel.ClientBase(Of ISISEASY.IEasy)
        Implements ISISEASY.IEasy
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SendInvoice(ByVal VKN As String, ByVal SenderAlias As String, ByVal ReceiverAlias As String, ByVal ByteData() As Byte) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.SendInvoice
            Return MyBase.Channel.SendInvoice(VKN, SenderAlias, ReceiverAlias, ByteData)
        End Function
        
        Public Function SendEnvelope(ByVal VKN As String, ByVal ByteData() As Byte) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.SendEnvelope
            Return MyBase.Channel.SendEnvelope(VKN, ByteData)
        End Function
        
        Public Function SendResponse(ByVal VKN As String, ByVal ETTN As String, ByVal Response As ISISEASY.ContractsCommercialResponseType, ByVal Reason As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.SendResponse
            Return MyBase.Channel.SendResponse(VKN, ETTN, Response, Reason)
        End Function
        
        Public Function GetInvoice(ByVal VKN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetInvoice
            Return MyBase.Channel.GetInvoice(VKN)
        End Function
        
        Public Function GetSingleInvoice(ByVal VKN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetSingleInvoice
            Return MyBase.Channel.GetSingleInvoice(VKN)
        End Function
        
        Public Function GetStatus(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetStatus
            Return MyBase.Channel.GetStatus(VKN, Direction, ETTN)
        End Function
        
        Public Function GetMultipleItemStatus(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTNList As System.Collections.Generic.List(Of String)) As System.Collections.Generic.List(Of ISISEASY.ContractsResponseType) Implements ISISEASY.IEasy.GetMultipleItemStatus
            Return MyBase.Channel.GetMultipleItemStatus(VKN, Direction, ETTNList)
        End Function
        
        Public Function GetSingleEnvelope(ByVal VKN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetSingleEnvelope
            Return MyBase.Channel.GetSingleEnvelope(VKN)
        End Function
        
        Public Function GetEnvelope(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetEnvelope
            Return MyBase.Channel.GetEnvelope(VKN, Direction, ETTN)
        End Function
        
        Public Function GetPostboxList(ByVal ReceiverVKN As String) As System.Collections.Generic.List(Of String) Implements ISISEASY.IEasy.GetPostboxList
            Return MyBase.Channel.GetPostboxList(ReceiverVKN)
        End Function
        
        Public Function GetPdfInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal PDFType As System.Collections.Generic.List(Of ISISEASY.EnumsPDFType)) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.GetPdfInvoice
            Return MyBase.Channel.GetPdfInvoice(VKN, Direction, ETTN, PDFType)
        End Function
        
        Public Function ReceiveDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.ReceiveDone
            Return MyBase.Channel.ReceiveDone(VKN, ETTN)
        End Function
        
        Public Function ReceiveEnvelopeDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.ReceiveEnvelopeDone
            Return MyBase.Channel.ReceiveEnvelopeDone(VKN, ETTN)
        End Function
        
        Public Function ReceiveInvoiceDone(ByVal VKN As String, ByVal ETTN As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.ReceiveInvoiceDone
            Return MyBase.Channel.ReceiveInvoiceDone(VKN, ETTN)
        End Function
        
        Public Function AcceptInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.AcceptInvoice
            Return MyBase.Channel.AcceptInvoice(VKN, Direction, ETTN, ResponseNote)
        End Function
        
        Public Function RejectInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.RejectInvoice
            Return MyBase.Channel.RejectInvoice(VKN, Direction, ETTN, ResponseNote)
        End Function
        
        Public Function ApproveInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.ApproveInvoice
            Return MyBase.Channel.ApproveInvoice(VKN, Direction, ETTN, ResponseNote)
        End Function
        
        Public Function DenyInvoice(ByVal VKN As String, ByVal Direction As ISISEASY.ContractsDirectionType, ByVal ETTN As String, ByVal ResponseNote As String, ByVal ReservedDate As System.Nullable(Of Date)) As ISISEASY.ContractsResponseType Implements ISISEASY.IEasy.DenyInvoice
            Return MyBase.Channel.DenyInvoice(VKN, Direction, ETTN, ResponseNote, ReservedDate)
        End Function
    End Class
End Namespace
